#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'wicd',
 'build_date': '2012-04-12 22:03:53 +0200',
 'clean': None,
 'date': '2012-04-12 22:03:49 +0200',
 'revision_id': 'd.paleino@gmail.com-20120412200349-ixrf62fh8u779hp3',
 'revno': '755'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
