#!/bin/sh
# postinst script for wicd

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    	if [ -f /etc/init.d/wicd ]; then
    		invoke-rc.d wicd stop
    	fi
    	
    	if [ -e /etc/rc0.d/*wicd ]; then
    		update-rc.d -f wicd remove >/dev/null
    	fi
    	
    	#rm -f /opt/wicd/*.pyc
    	
    	# Add Wicd to the startup sequence
    	# 80 to make sure that dbus is running when Wicd starts
    	#if which update-rc.d >/dev/null ; then
    	#	update-rc.d wicd defaults 80 20 >/dev/null
    	#fi
    	
    	# Start the daemon
    	if [ -f /etc/init.d/wicd ]; then
    		invoke-rc.d wicd start
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
