# Start fresh
rm -Rf $RPM_BUILD_ROOT
# Normal install
python setup.py install --root=$RPM_BUILD_ROOT --record=INSTALLED_FILES
# 'brp-compress' gzips the man pages without distutils knowing... fix this
sed -i -e 's@man/man\([[:digit:]]\)/\(.\+\.[[:digit:]]\)$@man/man\1/\2.gz@g' \
   INSTALLED_FILES
# Add files that will be generated by brp-python-bytecompile
find $RPM_BUILD_ROOT -type f -name "*.py" -printf "/%%P\n" | sed 's@\.py@&c@' >> INSTALLED_FILES
find $RPM_BUILD_ROOT -type f -name "*.py" -printf "/%%P\n" | sed 's@\.py@&o@' >> INSTALLED_FILES
